#42/flexibus/feature align login button
hpi-swt2/sport-portal pull request #108
Opened 2017-11-22 09:15 UTC by Blubl

Closes #42

2017-11-22 19:44 UTC, jkbe submitted a review, later dismissed

2017-11-22 19:44 UTC, jak-ing commented on app/views/application/_navbar.html.erb
> +      <%= menu_item t('devise.registrations.sign_in'), new_user_session_path, class: 'btn btn-default'%>
What about a German translation for `devise.regsitrations.sign_in`? Maybe that way, we can take a first step to integrating German translations gradually. I found some sample German translations of the entire devise locales YAML here: https://github.com/plataformatec/devise/wiki/I18n

2017-11-22 22:22 UTC, jak-ing commented
Could you provide some exact links here in the PR as to where you pulled the YAMLs from (for documentation...)?

2017-11-22 23:50 UTC, jonashering commented
Good sources for locale files:
* https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale (general)
* https://github.com/plataformatec/devise/wiki/I18n (for devise)

2017-11-22 23:57 UTC, jonashering commented
Good sources for locale files:
* https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale (general)
* https://github.com/plataformatec/devise/wiki/I18n (for devise)

2017-11-23 12:02 UTC, jak-ing commented on app/views/application/_navbar.html.erb
> +      <%= menu_item t('devise.registrations.sign_in'), new_user_session_path, class: 'btn btn-default'%>
Here is the PR with the locales #111

2017-11-24 15:45 UTC, jkbe requested changes

2017-11-24 15:45 UTC, jak-ing commented on app/views/application/_navbar.html.erb
>        <%= menu_divider %>
The devider messes up the layout on mobile:
![screen shot 2017-11-24 at 16 43 23](https://user-images.githubusercontent.com/15202881/33217067-c6c4153c-d136-11e7-8637-07dce74b710a.png)

2017-11-26 22:01 UTC, jak-ing commented on app/views/application/_navbar.html.erb
>        <%= menu_divider %>
Shouldn't be a big deal anymore after incorporating changes from `dev` because the 'Abmelden' button has moved into a dropdown menu by now.

2017-11-27 07:29 UTC, jkbe approved these changes

2017-11-27 07:33 UTC, merged