#60/swteam/input validation
hpi-swt2/sport-portal pull request #160
Opened 2017-11-28 14:41 UTC by Markus-Brand

Adds additional input validation for the sign up page:
Passwords have to fulfill these contidions:
-min. 8 characters
-at least 4 different characters
-not only numbers

Last Name can't be blank

2017-11-28 15:55 UTC, ErikBrendel approved these changes

2017-11-28 15:55 UTC, ErikBrendel commented on app/models/user.rb
> +    if password.present?
why this condition? Could it be non-present?

2017-11-28 15:55 UTC, ErikBrendel commented on features/input_validation.feature
> +  |  a1s2d3f      |  Passwort ist zu kurz (weniger als 8 Zeichen)                 |
thats not really beautiful, because you cannot test multi-lingual now. You could use the I18n translation keys here for example

2017-11-28 15:55 UTC, ErikBrendel commented on db/schema.rb
> -    t.date "startdate"
why the schema change?

2017-11-28 18:36 UTC, fpottbaecker requested changes

2017-11-28 18:36 UTC, Pottiman commented on app/models/user.rb
> +      errors.add :password, I18n.t('validations.not_only_numbers')
you might put the unless add the end of the line here.

2017-11-28 18:36 UTC, Pottiman commented on app/models/user.rb
> +      errors.add :password, I18n.t('validations.four_different_characters')
same here.

2017-11-28 18:36 UTC, Pottiman commented on app/models/user.rb
> +  validates :first_name, :last_name, presence: true
I think you usually put all method declarations below all validation declaration

2017-11-28 18:36 UTC, Pottiman commented on features/input_validation.feature
> +
Space — the final frontier. These are the voyages of the starship `develop`. Its ongoing mission — to program strange new apps — to seek out new smells and new optimizations — to boldly code where no man has coded before.

You could just use this example as a scenario specific example

2017-11-28 18:36 UTC, Pottiman commented on features/step_definitions/user.rb
> +  found_users = User.all.select do |user|
Please use `User.where(email: something, ...)` or `User.find_by(email: something, ...)`.

2017-11-28 18:36 UTC, Pottiman commented on features/input_validation.feature
> +    Given a new user a with a blank first name field
Maybe make this test more form specific.

You could just create a background like:
```
Background:
  Given A new user
  When he visits the new user page
  And he enters his information
```

and a specific scenario like:

```
  When he enters an empty first name
  And submits
  Then he should not be able to sign up
```

2017-11-28 18:36 UTC, Pottiman commented on features/step_definitions/user.rb
> +And(/^the page should show (.*)$/) do |message|
This might cause some ambiguity later down the line. Could you wrap the parameter in quotes?

2017-11-28 18:36 UTC, Pottiman commented on features/step_definitions/user.rb
> +end
Please do not forget empty new lines at the end of files

2017-11-28 18:36 UTC, Pottiman commented on spec/models/user_spec.rb
> +  it 'is not valid if password has not four different characters' do
Maybe "less than"

2017-12-05 14:46 UTC, fpottbaecker approved these changes

2017-12-05 14:47 UTC, merged