Swteam/#169: Third place Match
hpi-swt2/sport-portal pull request #361
Opened 2018-01-16 16:05 UTC by ErikBrendel

With this PR, a **match for place 3** gets created for every Tournament.

2018-01-16 19:50 UTC, fpottbaecker requested changes

2018-01-16 19:50 UTC, Pottiman commented on app/models/tournament.rb
> +    matches.each do |match|
`matches.find`

2018-01-16 19:50 UTC, Pottiman commented on app/models/tournament.rb
>      matches.each do |match|
`matches.find`

2018-01-17 11:04 UTC, Pottiman commented on app/models/tournament.rb
> +    matches.where(gameday: finale_gameday).first
You can use `find_by`

2018-01-17 13:40 UTC, fpottbaecker approved these changes

2018-01-17 14:00 UTC, merged

2018-01-17 14:00 UTC, ErikBrendel commented
closes #169