added seperate match  edit view for admin and other users
hpi-swt2/sport-portal pull request #412
Opened 2018-01-21 16:27 UTC by akuchinke

2018-01-22 07:31 UTC, nikriek requested changes

2018-01-22 07:31 UTC, nikriek commented on app/views/matches/_form.html.erb
> +      <% if current_user!=nil and current_user.admin==true %>
Please use `nil?` or `blank?` and maybe add a helper function instead of the ugly `== true`

2018-01-27 14:21 UTC, citron0xa9 approved these changes
Looks good, maybe fix indentation

2018-01-27 14:23 UTC, nikriek approved these changes

2018-01-30 15:53 UTC, merged