Kickerz/#125/create rankings for event
hpi-swt2/sport-portal pull request #460
Opened 2018-01-29 13:48 UTC by jonasnoki

2018-01-29 14:44 UTC, bakoe commented
@jonasnoki Please give the PR a name that represents the actual changes included in the PR better (something like “Generate rankings only for leagues and adjust the ranking table wording”. At the moment, it sounds like the PR introduces the rankings for events which was done in #125 already.

2018-01-30 10:45 UTC, birneamstiel requested changes
minor changes :-)

2018-01-30 10:45 UTC, birneamstiel commented on app/controllers/leagues_controller.rb
> +  # GET /events/1/ranking
Adjust comment

2018-01-30 10:45 UTC, birneamstiel commented on spec/features/event/ranking_event_spec.rb
>      @event = FactoryBot.create :rankinglist
Please rename this file to `rankinglist_spec.rb`

2018-01-30 10:45 UTC, birneamstiel commented on spec/features/event/ranking_league_spec.rb
> +require 'rails_helper'
Please rename this file to `ranking_event_spec.rb` and add negative tests for Tournaments and Rankinglists regarding the generation of Rankings

2018-01-30 10:45 UTC, birneamstiel commented on spec/features/event/ranking_league_spec.rb
> +    visit leagues_ranking_path(event)
Maybe add further assertions and not just visit the page and hope that an error occurs when there is no route(?)

2018-01-30 10:45 UTC, birneamstiel commented on spec/routing/events_routing_spec.rb
> -    it 'routes to #ranking' do
Add negative test:
```ruby
it "doesn't route to #ranking" do
  expect(get: "/events/1/ranking").to_not route_to("events#ranking", id: "1")
end
```

2018-01-30 10:45 UTC, birneamstiel commented on spec/views/events/show.html.erb_spec.rb
> -    it 'has a ranking button' do
Add negative test:
```ruby
it "doesn't have a ranking button" do		
  render		
  expect(rendered).to_not have_content(t('events.show.to_ranking'))		
end
```

2018-01-30 11:52 UTC, bakoe approved these changes
LGTM code-wise! Have tested together with @birneamstiel whether it works in Browser … it does. 🙂

2018-01-30 13:01 UTC, birneamstiel approved these changes

2018-01-30 13:07 UTC, merged