custom have fun messages for team mails. ref #308
hpi-swt2/sport-portal pull request #496
Opened 2018-01-31 13:30 UTC by conradlempert

2018-02-01 18:21 UTC, birneamstiel approved these changes

2018-02-01 19:34 UTC, bakoe approved these changes
LGTM! 👍 I have also confirmed that the change is working by using `rails c` to provoke both e-mail notification events – the localizations are used as one would expect.

2018-02-01 19:34 UTC, bakoe commented on app/views/team_mailer/team_registered_to_event.html.erb
> +<p><%= t('.have_fun') %></p>
Nice find that we can use `.have_fun` without explicitly defining e. g. `user_added_to_team` as the locale to look into for the localization. 👍

2018-02-01 19:39 UTC, bakoe requested changes
Although not explicitly defined in the initial user story #308 or in @svitlanakalancha's change request stated in Slack (see channel #307-308-coordination), I'm pretty sure that @svitlanakalancha especially wanted that User's don't get the ”Viel Erfolg beim Training!“ message when matches are canceled and when events are canceled/finished. Could you maybe integrate this in this PR as well @conradlempert?

2018-02-01 19:41 UTC, bakoe commented
@conradlempert See the following message from the Slack channel for explanation about what I meant regarding @svitlanakalancha's change request:

<img width="567" alt="ohne titel 3" src="https://user-images.githubusercontent.com/807665/35699380-2d779814-0790-11e8-90f4-c6d850f75025.png">

Maybe just remove the `have_fun` part from the notifications about the following events?

- match being canceled
- event being canceled
- event being finished

2018-02-03 18:45 UTC, bakoe approved these changes

2018-02-03 18:45 UTC, merged