Swteam/#484/remove unused gametypes
hpi-swt2/sport-portal pull request #509
Opened 2018-02-02 12:23 UTC by Markus-Brand

2018-02-02 12:45 UTC, ErikBrendel approved these changes

2018-02-02 12:45 UTC, ErikBrendel commented on config/locales/de.yml
>        ko: "KO"
ko?

2018-02-02 12:55 UTC, pawelsoundso approved these changes

2018-02-02 13:42 UTC, fpottbaecker requested changes

2018-02-02 13:42 UTC, Pottiman commented on app/views/events/show.html.erb
> +  <% if @event.type != 'Tournament' %>
`unless @event.is_a? Tournament`

2018-02-03 17:56 UTC, ErikBrendel commented on app/views/events/show.html.erb
> +  <% if @event.type != 'Tournament' %>
Would this be better?

2018-02-04 19:55 UTC, fpottbaecker approved these changes

2018-02-04 20:15 UTC, merged