Flexibus/#497/profile page design
hpi-swt2/sport-portal pull request #533
Opened 2018-02-04 20:18 UTC by jonashering

Closes #497.

Finishes redesign of profile site.

2018-02-04 22:38 UTC, jkbe requested changes
Looks good. Just one minor issue and a suggestion.

2018-02-04 22:38 UTC, jak-ing commented on app/views/devise/registrations/show.html.erb
> +                    edit_user_path(@user), :class => 'btn btn-default btn-save-edit-user btn-centered' %>
It seems all properties of `btn-default` are overwritten so it's safe to remove.

2018-02-04 22:38 UTC, jak-ing commented on app/assets/stylesheets/users.css
> +.profile-image {
Why not make this an `id` for a change? 👯

2018-02-05 10:06 UTC, jonashering commented
@jak-ing Last commit addresses changes requested. Please recheck!

2018-02-05 10:15 UTC, jkbe approved these changes

2018-02-05 12:00 UTC, merged