Flexibus/#380/events view as tiles
hpi-swt2/sport-portal pull request #557
Opened 2018-02-06 18:40 UTC by jcremerius

2018-02-06 18:42 UTC, jak-ing commented
Please move the corresponding issue to "in review" yourself on Waffle.io so that we have a correct overview of the state of tickets for Kanban!

2018-02-07 12:14 UTC, Jeilef commented on app/models/event.rb
>    end
does this method really have to be in the Events model?

2018-02-07 15:17 UTC, jcremerius commented on app/models/event.rb
>    end
Where would you place it?

2018-02-08 12:58 UTC, jkbe requested changes

2018-02-08 12:58 UTC, jak-ing commented on app/assets/stylesheets/tile.css
> +@media screen and (max-width : 799px) and (min-width: 481px) {
What do we have this block for? The condition selects a subset of elements of the `@media`'s condition above and the CSS values are the same. Remove?

2018-02-08 13:01 UTC, jkbe submitted a review, later dismissed
LGTM but...

2018-02-08 14:34 UTC, jkbe approved these changes

2018-02-08 14:34 UTC, merged